#!/bin/sh
# 编写新脚本
if [ $# = 0 ];then exit 0 ;fi

filename=$1

file=`which $filename`

if [ $? != 0 ]; then file=$AUTO/commands/$filename; fi
# if [ $? != 0 ]; then exit 0; fi


if [ $HOSTNAME = sfront ]; then
	rmate $file

else
	atom $file
fi


chmod +x $file;
