#!/bin/sh
isfront=`echo $HOSTNAME|grep -c front`
if [ $isfront -eq 0 ];then /public/bin/pscpu-node;exit;fi

rm ~/node_available
if [ $# == 0 ];then nodefile=node_av;
else nodefile=$1;fi
for i in `cat ~/$nodefile`
do
    rsh $i "/public/bin/pscpuall-single $i" </dev/null;
done
cat ~/node_available
