#!/bin/sh
if [ $# = 0 ];then exit 0 ;fi

filename=$1

file=`which $filename`

if [ $? != 0 ]; then file=~/lhrkits/pubkit/$filename; fi
# if [ $? != 0 ]; then exit 0; fi


if [ $HOSTNAME = sfront ]; then
	rmate $file

else
	subl $file
fi


chmod +x $file;
